# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import centralServer_pb2 as centralServer__pb2


class centralServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.register = channel.unary_unary(
                '/centralServer.centralServer/register',
                request_serializer=centralServer__pb2.registerRequest.SerializeToString,
                response_deserializer=centralServer__pb2.registerResponse.FromString,
                )
        self.map = channel.unary_unary(
                '/centralServer.centralServer/map',
                request_serializer=centralServer__pb2.mapRequest.SerializeToString,
                response_deserializer=centralServer__pb2.mapResponse.FromString,
                )
        self.terminate = channel.unary_unary(
                '/centralServer.centralServer/terminate',
                request_serializer=centralServer__pb2.Empty.SerializeToString,
                response_deserializer=centralServer__pb2.terminateResponse.FromString,
                )


class centralServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def map(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def terminate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_centralServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'register': grpc.unary_unary_rpc_method_handler(
                    servicer.register,
                    request_deserializer=centralServer__pb2.registerRequest.FromString,
                    response_serializer=centralServer__pb2.registerResponse.SerializeToString,
            ),
            'map': grpc.unary_unary_rpc_method_handler(
                    servicer.map,
                    request_deserializer=centralServer__pb2.mapRequest.FromString,
                    response_serializer=centralServer__pb2.mapResponse.SerializeToString,
            ),
            'terminate': grpc.unary_unary_rpc_method_handler(
                    servicer.terminate,
                    request_deserializer=centralServer__pb2.Empty.FromString,
                    response_serializer=centralServer__pb2.terminateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'centralServer.centralServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class centralServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/centralServer.centralServer/register',
            centralServer__pb2.registerRequest.SerializeToString,
            centralServer__pb2.registerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def map(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/centralServer.centralServer/map',
            centralServer__pb2.mapRequest.SerializeToString,
            centralServer__pb2.mapResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def terminate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/centralServer.centralServer/terminate',
            centralServer__pb2.Empty.SerializeToString,
            centralServer__pb2.terminateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
