# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: centralServer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x63\x65ntralServer.proto\x12\rcentralServer\"4\n\x0fregisterRequest\x12\x10\n\x08serverID\x18\x01 \x01(\t\x12\x0f\n\x07keyList\x18\x02 \x03(\x05\"2\n\x10registerResponse\x12\x1e\n\x16\x61mountOfRegisteredKeys\x18\x01 \x01(\x05\"\x19\n\nmapRequest\x12\x0b\n\x03key\x18\x01 \x01(\x05\"\x1f\n\x0bmapResponse\x12\x10\n\x08serverID\x18\x01 \x01(\t\"3\n\x11terminateResponse\x12\x1e\n\x16\x61mountOfRegisteredKeys\x18\x01 \x01(\x05\"\x07\n\x05\x45mpty2\xdf\x01\n\rcentralServer\x12K\n\x08register\x12\x1e.centralServer.registerRequest\x1a\x1f.centralServer.registerResponse\x12<\n\x03map\x12\x19.centralServer.mapRequest\x1a\x1a.centralServer.mapResponse\x12\x43\n\tterminate\x12\x14.centralServer.Empty\x1a .centralServer.terminateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'centralServer_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REGISTERREQUEST']._serialized_start=38
  _globals['_REGISTERREQUEST']._serialized_end=90
  _globals['_REGISTERRESPONSE']._serialized_start=92
  _globals['_REGISTERRESPONSE']._serialized_end=142
  _globals['_MAPREQUEST']._serialized_start=144
  _globals['_MAPREQUEST']._serialized_end=169
  _globals['_MAPRESPONSE']._serialized_start=171
  _globals['_MAPRESPONSE']._serialized_end=202
  _globals['_TERMINATERESPONSE']._serialized_start=204
  _globals['_TERMINATERESPONSE']._serialized_end=255
  _globals['_EMPTY']._serialized_start=257
  _globals['_EMPTY']._serialized_end=264
  _globals['_CENTRALSERVER']._serialized_start=267
  _globals['_CENTRALSERVER']._serialized_end=490
# @@protoc_insertion_point(module_scope)
