# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cserver.proto\x12\x06server\"+\n\rinsertRequest\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\t\"!\n\x0einsertResponse\x12\x0f\n\x07success\x18\x01 \x01(\x05\"\x1d\n\x0e\x63onsultRequest\x12\x0b\n\x03key\x18\x01 \x01(\x05\" \n\x0f\x63onsultResponse\x12\r\n\x05value\x18\x01 \x01(\t\"*\n\x0f\x61\x63tivateRequest\x12\x17\n\x0f\x63\x65ntralServerID\x18\x01 \x01(\t\"1\n\x10\x61\x63tivateResponse\x12\x1d\n\x15\x61mountOfActivatedKeys\x18\x01 \x01(\x05\" \n\x11terminateResponse\x12\x0b\n\x03key\x18\x01 \x01(\x05\"\x07\n\x05\x45mpty2\xf3\x01\n\x06server\x12\x37\n\x06insert\x12\x15.server.insertRequest\x1a\x16.server.insertResponse\x12:\n\x07\x63onsult\x12\x16.server.consultRequest\x1a\x17.server.consultResponse\x12=\n\x08\x61\x63tivate\x12\x17.server.activateRequest\x1a\x18.server.activateResponse\x12\x35\n\tterminate\x12\r.server.Empty\x1a\x19.server.terminateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_INSERTREQUEST']._serialized_start=24
  _globals['_INSERTREQUEST']._serialized_end=67
  _globals['_INSERTRESPONSE']._serialized_start=69
  _globals['_INSERTRESPONSE']._serialized_end=102
  _globals['_CONSULTREQUEST']._serialized_start=104
  _globals['_CONSULTREQUEST']._serialized_end=133
  _globals['_CONSULTRESPONSE']._serialized_start=135
  _globals['_CONSULTRESPONSE']._serialized_end=167
  _globals['_ACTIVATEREQUEST']._serialized_start=169
  _globals['_ACTIVATEREQUEST']._serialized_end=211
  _globals['_ACTIVATERESPONSE']._serialized_start=213
  _globals['_ACTIVATERESPONSE']._serialized_end=262
  _globals['_TERMINATERESPONSE']._serialized_start=264
  _globals['_TERMINATERESPONSE']._serialized_end=296
  _globals['_EMPTY']._serialized_start=298
  _globals['_EMPTY']._serialized_end=305
  _globals['_SERVER']._serialized_start=308
  _globals['_SERVER']._serialized_end=551
# @@protoc_insertion_point(module_scope)
